### ISSUE TITLE
Add request delay?

### ISSUE THREAD

**Issue by jamen** [egoist/aimer#1]
Some websites have content injected after they load.

**Comment by jamen** [comment]
Never mind, not sure exactly how that would work.

**Comment by egoist** [comment]
Umm, this is possible. 

We may have to mock a browser env using `phantomjs` or [nightmare](https://github.com/segmentio/nightmare) , however still worth a try. 🤔

**Comment by egoist** [comment]
😅  `1.0.0` allows us to achieve this via `nightmare` 🎉

**Comment by jamen** [comment]
Awesome. ;D
